initializer:
  tonic:
    url: http://localhost:8080
    #url: https://tcin-j-dev-service.apps.ocp-app1-dij1-bo.hp.csh-dijon.ramage (ajouter contrat, sun security block)
  stump:
    url: http://stump-url:8080
  human:
    url: http://human-url:8080

server:
  port: 9000

springdoc:
  api-docs:
    version: openapi_3_0
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html