initializer:
  tonic:
    url: http://localhost:8080
    #url: https://tcin-j-dev-service.apps.ocp-app1-dij1-bo.hp.csh-dijon.ramage (ajouter contrat, sun security block)
  stump:
    url: http://stump-url:8080
  human:
    url: http://human-url:8080
  features:
    tonic:
      - toni-starter-security-authapp-v2-client
      - toni-starter-security-authapp-v3-client
      - toni-starter-security-authapp-v3-server
      - toni-starter-security-oauth2-agent-server
      - toni-starter-jdbc
      - toni-starter-amazon-s3
      - toni-starter-client-espoir
      - toni-starter-client-pat
      - toni-contract-openapi
      - toni-contract-avro
    stump:
      - test
      - test2
    human:
      - test
      - test2

server:
  port: 9000

springdoc:
  api-docs:
    version: openapi_3_0
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html