initializer:
  tonic:
    url: http://localhost:8080
  metric:
    url: http://localhost:9002/poc-metrique-instances-stump/public/rest

server:
  port: 9000

logging:
  level:
    org.springframework: info
    fr.cnam: debug
