initializer:
  tonic:
    url: ${TONIC_URL}
    default:
      group-id: com.example
      artifact-id: tonic

openapi:
  # chemin d'accès du contrat OpenAPI
  # utilisé par le controller custom SpringDoc pour fournir à swagger-ui
  # le document OpenAPI original, et pas un document regénéré à partir du code
  # (fonctionnement par défaut)
  contract.location: "classpath:openapi-facade.yml"