openapi: 3.0.3
info:
  title: API Facade DDST (FAIN_J)
  description: |
    Service facade pour les instanciateurs de starter kits DDST
  version: 0.0.1-SNAPSHOT
components:
  schemas:
    Features:
      type: array
      items:
        type: string
    ComponentType:
      type: string
      enum:
        - TONIC
        - HUMAN
      #        - STUMP
      #        - CONTRAT-OPENAPI
      #        - CONTRAT-AVRO
      #        - CONTRAT-SOAP
      #        - LIB-JAVA
      #        - LIB-NODE
      default: TONIC
    ComponentTypes:
      type: array
      items:
        $ref: '#/components/schemas/ComponentType'
paths:
  /type-composant:
    get:
      summary: Obtenir les types de composants disponibles
      description: Récupère la liste des types de composants supportés par l'API
      operationId: getComponentTypes
      responses:
        '200':
          description: Liste des types de composants disponibles
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComponentTypes'
        '500':
          description: Erreur interne du serveur

  /instanciate:
    get:
      summary: Créer une instance du type demandé
      description: Créer une instance du type demandé, avec les fonctionnalités requises
      operationId: getSourceZip
      parameters:
        - name: typeDeComposant
          in: query
          description: Kit à instancier
          required: true
          schema:
            $ref: '#/components/schemas/ComponentType'
        - name: nomDuComposant
          in: query
          description: Nom du composant à générer
          required: true
          schema:
            type: string
        - name: groupId
          in: query
          description: Identifiant de groupe pour le projet Maven
          required: false
          schema:
            type: string
        - name: artifactId
          in: query
          description: Identifiant d'artefact pour le projet Maven
          required: false
          schema:
            type: string
        - name: features
          in: query
          description: Fonctionnalités à instancier
          required: false
          schema:
            $ref: '#/components/schemas/Features'
          style: form
          explode: true
      responses:
        '200':
          description: Retourne une archive zip contenant les sources correspondant aux paramètres demandés
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: Valeur de statut invalide

  /features:
    get:
      summary: Obtenir les fonctionnalités disponibles
      description: Récupère la liste des fonctionnalités pour le type de composant spécifié
      operationId: getFeatures
      parameters:
        - name: typeDeComposant
          in: query
          description: Type de composant (ex. HUMAN, STUMP, TONIC, CONTRAT-OPENAPI, CONTRAT-AVRO, CONTRAT-SOAP, LIB-JAVA, LIB-NODE)
          required: true
          schema:
            $ref: '#/components/schemas/ComponentType'
      responses:
        '200':
          description: Réponse réussie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Features'
        '400':
          description: Requête invalide