openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: https://tcin-j-dev-service.apps.ocp-app1-dij1-bo.hp.csh-dijon.ramage
    description: Generated server url
paths:
  /starter.zip:
    get:
      tags:
        - tonic-project-generation-controller
      operationId: springZip
      parameters:
        - name: dependencies
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
        - name: groupId
          in: query
          required: false
          schema:
            type: string
        - name: artifactId
          in: query
          required: false
          schema:
            type: string
        - name: name
          in: query
          required: false
          schema:
            type: string
        - name: type
          in: query
          required: false
          schema:
            type: string
        - name: description
          in: query
          required: false
          schema:
            type: string
        - name: version
          in: query
          required: false
          schema:
            type: string
        - name: bootVersion
          in: query
          required: false
          schema:
            type: string
        - name: packaging
          in: query
          required: false
          schema:
            type: string
        - name: applicationName
          in: query
          required: false
          schema:
            type: string
        - name: language
          in: query
          required: false
          schema:
            type: string
        - name: packageName
          in: query
          required: false
          schema:
            type: string
        - name: javaVersion
          in: query
          required: false
          schema:
            type: string
        - name: baseDir
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            'application/zip':
              schema:
                type: string
                format: binary
components:
  schemas:
    ProjectRequest:
      type: object
      properties:
        dependencies:
          type: array
          items:
            type: string
        name:
          type: string
        type:
          type: string
        description:
          type: string
        groupId:
          type: string
        artifactId:
          type: string
        version:
          type: string
        bootVersion:
          type: string
        packaging:
          type: string
        applicationName:
          type: string
        language:
          type: string
        packageName:
          type: string
        javaVersion:
          type: string
        baseDir:
          type: string